Parameters:
  EnvironmentSize:
    Type: String
    Default: SMALL
  DatabaseName:
    Type: String
    Default: wordpress
  DatabaseUser:
    Type: String
    Default: user1
  DatabasePassword:
    Type: String
    Default: iso*help
    NoEcho: true
Mappings:
  RegionMap:
    ap-south-1:
      "LINUX" : "ami-0cb0e70f44e1a4bb5" 
  InstanceSize:
    SMALL:
      "EC2" : "t2.micro"
      "DB" : "db.t2.micro"
Resources:
  DB:
    Type: "AWS::RDS::DBInstance"
    Properties:
      AllocatedStorage: 5
      StorageType: gp2
      DBInstanceClass: !FindInMap [InstanceSize, !Ref EnvironmentSize, DB] 
      DBName: !Ref DatabaseName
      Engine: MySQL
      MasterUsername: !Ref DatabaseUser
      MasterUserPassword: !Ref DatabasePassword
      VPCSecurityGroups:
        - !Ref DBSG
  EC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: !FindInMap [RegionMap, !Ref "AWS::Region", LINUX] # Dynamic mapping + Pseudo Parameter
      InstanceType: !FindInMap [InstanceSize, !Ref EnvironmentSize, EC2]
      SecurityGroupIds:
        - !Ref SG
      KeyName: testkeypair
      UserData:
        "Fn::Base64":
          !Sub |
            #!/bin/bash
            yum install httpd php mysql php-mysql -y
            yum update -y
            chkconfig httpd on
            service httpd start
            cd /var/www/html
            wget https://wordpress.org/wordpress-4.6.10.tar.gz
            tar -zxvf wordpress-4.6.10.tar.gz --strip 1
            cp wp-config-sample.php wp-config.php
            sed -i 's/database_name_here/${DatabaseName}/g' wp-config.php
            sed -i 's/localhost/${DB.Endpoint.Address}/g' wp-config.php
            sed -i 's/username_here/${DatabaseUser}/g' wp-config.php
            sed -i 's/password_here/${DatabasePassword}/g' wp-config.php
  SG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SG to allow http access
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          ToPort: 80
          FromPort: 80
  DBSG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: SG to allow DB access
      VpcId: vpc-3ad6fc53
      SecurityGroupIngress:
        - CidrIp: 172.31.0.0/18
          IpProtocol: tcp
          ToPort: 3306
          FromPort: 3306
